spring.application.name=payment-service
server.port=5006

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/payment?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Mysql123!

razorpay.api.key="your razorpay api key"
razorpay.api.secret="your razorpay api secret"

stripe.api.key="your stripe api key"