
server:
  port: 5001
spring:
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/userdb?createDatabaseIfNotExist=true
    username: root
    password: Mysql123!
    driver-class-name: com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://localhost:8070/eureka/"